name: Gclone Bot Set Up

on:
  workflow_dispatch:
    inputs:
      join:
        description: 'https://t.me/drivetalkကို joinပြီးပြီလား? Join ပြီးလျှင်Yesနှိပ်ပါ မjoin ရသေးလျှင် joinပြီးမှဒီBot သုံးပါ'
        required: true
      token:
        description: 'Token.pickleဖိုင်တင်ပြီးပြီလား? ပြီးလျှင်Yesနှိပ်ပါ မတင်ရသေးလျှင် တင်ပြီးမှဒီBot သုံးပါ'
        required: true
      
jobs: 
  build:
    name: CloneBot Running
    runs-on: ubuntu-latest
    steps:
      - name: Preparing Source Code
        uses: actions/checkout@v2
      - name: Installing Required Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Preparing Bot Token
        run: echo BOT_TOKEN = '"${{ secrets.BOT_TOKEN }}"' >> bot/config.py
      - name: Installing Python3 and dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Running the bot
        run: |
          python3 -m bot
