name: Gclone Bot Set Up

on:
  workflow_dispatch:
    inputs:
      BOT_TOKEN:
        description: 'BotFatherမှToken'
        required: false
      
jobs: 
  build:
    name: CloneBot Running
    runs-on: ubuntu-latest
    steps:
      - name: Preparing Source Code
        uses: actions/checkout@v2
      - name: Installing Required Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Preparing Bot Token
        run: echo BOT_TOKEN = '"${{ secrets.BOT_TOKEN }}"' >> bot/config.py
      - name: Installing Python3 and dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Running the bot
        run: |
          python3 -m bot
