name: ⚫FcloneRun

on:
  workflow_dispatch:
    inputs:
      BOT_TOKEN:
        description: 'BotFatherမှToken'
        required: true
      
jobs:
  RUNNING:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Create Image
        run: docker pull npt13/fclone
      - name: Run Image
        run: docker run --env BOT_TOKEN=${{ secrets.BOT_TOKEN }} --env OWNER_ID=123456789 npt13/fclone
