name: ⭐MLTB

on:
  workflow_dispatch:
    inputs:
      join:
        description: '@drivetalk ကို joinပြီးပြီလား? Join ပြီးလျှင် y နှိပ်ပါ မjoin ရသေးလျှင် joinပြီးမှဒီBot သုံးပါ'
        required: true
      
jobs:
  RUNNING:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Create Image
        run: docker pull npt13/mltbkore
      - name: Run Image
        run: docker run --env CONFIG_FILE_URL=${{ secrets.CONFIG_FILE_URL }} npt13/mltbkore
